on:
  workflow_dispatch:
  push:

jobs:
  FoD-SAST-Scan:
    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4
        with:
          ref: develop

      # Import fod.sarif
      - name: Import Results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ./fod.sarif

      # Import ssc.sarif
      - name: Import Results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ./ssc.sarif
